version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "decentrabox-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i4p7ofcbrcpo"
s3_prefix = "decentrabox-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
