AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  decentrabox-api

  SAM Template for decentrabox-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 250
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  MagicLinkFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: magic-link/
      Handler: app.lambdaHandler
      Layers:
        - !Ref DecentraLayer
      Runtime: nodejs14.x
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
      Events:
        MagicLink:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /send-magiclink
            Method: get
  GetApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-api/
      Handler: app.lambdaHandler
      Layers:
        - !Ref DecentraLayer
      Runtime: nodejs14.x
      Events:
        GetApiLink:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getapi
            Method: get
  DecentraLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: decentrabox-dependencies
        Description: Dependencies for decentrabox lambda
        ContentUri: dependencies/
        CompatibleRuntimes:
          - nodejs14.x
        LicenseInfo: 'MIT'
        RetentionPolicy: Retain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MagicLinkApi:
    Description: "API Gateway endpoint URL for Prod stage for Magic Link function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send-magiclink/"
  MagicLinkFunction:
    Description: "Magic Link Lambda Function ARN"
    Value: !GetAtt MagicLinkFunction.Arn
  MagicLinkFunctionIamRole:
    Description: "Implicit IAM Role created for Magic Link function"
    Value: !GetAtt MagicLinkFunctionRole.Arn
    #GetApi
  GetApiApi:
    Description: "API Gateway endpoint URL for Prod stage for Get API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getapi/"
  GetApiFunction:
    Description: "Get Api Lambda Function ARN"
    Value: !GetAtt GetApiFunction.Arn
  GetApiFunctionIamRole:
    Description: "Implicit IAM Role created for Get Api function"
    Value: !GetAtt GetApiFunctionRole.Arn
